version: '2'
services:
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300
      
  logstash:
    image: logstash_6.1.3
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5044:5044
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
    
    
  curator: 
    image: curator
    links: 
    - elasticsearch
   
    
    