FROM docker.elastic.co/logstash/logstash-oss:6.1.3

VOLUME ["/data"]

ADD logstash.conf /data/logstash.conf
ADD patterns /data/patterns

WORKDIR /data

CMD ["../opt/logstash/bin/logstash", "-f", "/data/logstash.conf"]